import React, { useState, useEffect } from 'react';
import { PieChart, Pie, Cell, ResponsiveContainer, Legend, Tooltip, BarChart, Bar, XAxis, YAxis, CartesianGrid } from 'recharts';

// Function to get today's date in local time (YYYY-MM-DD)
const getTodayDate = () => {
  const today = new Date();
  const yyyy = today.getFullYear();
  const mm = String(today.getMonth() + 1).padStart(2, '0');
  const dd = String(today.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
};

function App() {
  // Theme state for Dark Mode
  const [isDarkMode, setIsDarkMode] = useState(() => {
    const savedTheme = localStorage.getItem('theme');
    return savedTheme === 'dark';
  });

  // Transaction Type State for Form Input
  const [txnType, setTxnType] = useState('expense'); 

  // Input fields state
  const [txnName, setTxnName] = useState('');
  const [txnAmount, setTxnAmount] = useState('');
  const [txnCategory, setTxnCategory] = useState('Food');
  const [txnDate, setTxnDate] = useState(getTodayDate());
  
  // Recurring Checkbox State
  const [isRecurring, setIsRecurring] = useState(false);

  // Budget state
  const [monthlyBudget, setMonthlyBudget] = useState(() => {
    const savedBudget = localStorage.getItem('budget');
    return savedBudget ? parseFloat(savedBudget) : 0;
  });

  // Top Dashboard Filter (Main Month Selection)
  const [selectedMonth, setSelectedMonth] = useState(getTodayDate().substring(0, 7));
  const [widgetSelection, setWidgetSelection] = useState('Highest');

  // Bottom History Filter States
  const [historyTypeFilter, setHistoryTypeFilter] = useState('All'); 
  const [historyCategoryFilter, setHistoryCategoryFilter] = useState('All');
  const [historyDateFilter, setHistoryDateFilter] = useState(''); 

  // Load and migrate initial transactions from localStorage
  const [transactionsList, setTransactionsList] = useState(() => {
    const savedTransactions = localStorage.getItem('transactions');
    if (savedTransactions) return JSON.parse(savedTransactions);
    return [];
  });

  // Load Recurring Templates
  const [recurringList, setRecurringList] = useState(() => {
    const savedRecurring = localStorage.getItem('recurringList');
    if (savedRecurring) return JSON.parse(savedRecurring);
    return [];
  });

  // Pagination state
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 5;

  // Categories definitions
  const expenseCategories = ['Food', 'Transport', 'Bills', 'Entertainment', 'Other'];
  const incomeCategories = ['Salary', 'Business', 'Investments', 'Other'];
  const activeCategories = txnType === 'income' ? incomeCategories : expenseCategories;

  // Effect to handle Dark Mode class
  useEffect(() => {
    if (isDarkMode) {
      document.documentElement.classList.add('dark');
      localStorage.setItem('theme', 'dark');
    } else {
      document.documentElement.classList.remove('dark');
      localStorage.setItem('theme', 'light');
    }
  }, [isDarkMode]);

  // Save data to localStorage automatically
  useEffect(() => {
    localStorage.setItem('transactions', JSON.stringify(transactionsList));
  }, [transactionsList]);

  useEffect(() => {
    localStorage.setItem('recurringList', JSON.stringify(recurringList));
  }, [recurringList]);

  useEffect(() => {
    localStorage.setItem('budget', monthlyBudget.toString());
  }, [monthlyBudget]);

  // Auto-Process Recurring Bills on App Load
  useEffect(() => {
    const currentMonthPrefix = getTodayDate().substring(0, 7);
    let hasUpdates = false;
    let autoGeneratedTxns = [];

    const updatedRecurringList = recurringList.map(item => {
      if (item.lastProcessedMonth < currentMonthPrefix) {
        hasUpdates = true;
        autoGeneratedTxns.push({
          id: Date.now() + Math.random(),
          type: item.type,
          name: `${item.name} (Auto)`,
          amount: item.amount,
          category: item.category,
          date: `${currentMonthPrefix}-01` 
        });
        return { ...item, lastProcessedMonth: currentMonthPrefix };
      }
      return item;
    });

    if (hasUpdates) {
      setRecurringList(updatedRecurringList);
      setTransactionsList(prev => [...autoGeneratedTxns, ...prev]);
    }
  }, []); 

  // Reset pagination when bottom filters or top month selection changes
  useEffect(() => {
    setCurrentPage(1);
  }, [historyTypeFilter, historyCategoryFilter, historyDateFilter, selectedMonth]);

  // Update default category when switching form tabs
  useEffect(() => {
    if (txnType === 'income') setTxnCategory('Salary');
    else setTxnCategory('Food');
  }, [txnType]);

  // Reset category history filter if it doesn't match the selected type filter
  useEffect(() => {
    setHistoryCategoryFilter('All');
  }, [historyTypeFilter]);

  // Function to handle form submission
  const handleAddTransaction = (e) => {
    e.preventDefault();
    if (!txnName || !txnAmount || !txnDate) {
      alert("Please fill in all fields!");
      return;
    }

    const newTransaction = {
      id: Date.now(),
      type: txnType,
      name: txnName,
      amount: parseFloat(txnAmount),
      category: txnCategory,
      date: txnDate
    };

    setTransactionsList([newTransaction, ...transactionsList]);

    if (isRecurring) {
      const newRecurring = {
        id: Date.now() + Math.random(),
        type: txnType,
        name: txnName,
        amount: parseFloat(txnAmount),
        category: txnCategory,
        lastProcessedMonth: getTodayDate().substring(0, 7)
      };
      setRecurringList([...recurringList, newRecurring]);
    }
    
    setTxnName('');
    setTxnAmount('');
    setTxnDate(getTodayDate()); 
    setIsRecurring(false);
    setCurrentPage(1);
  };

  const handleDeleteTransaction = (id) => {
    const updatedList = transactionsList.filter(txn => txn.id !== id);
    setTransactionsList(updatedList);
  };

  const handleClearAll = () => {
    if (window.confirm("Are you sure you want to clear all history? This action cannot be undone.")) {
      setTransactionsList([]);
      setRecurringList([]);
      setCurrentPage(1);
    }
  };

  // --- NEW FEATURE: Backup Data to JSON ---
  const handleBackupData = () => {
    const dataToBackup = {
      transactions: transactionsList,
      recurringList: recurringList,
      budget: monthlyBudget
    };
    
    const jsonString = JSON.stringify(dataToBackup, null, 2);
    const blob = new Blob([jsonString], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = `SmartWallet_Backup_${getTodayDate()}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // --- NEW FEATURE: Restore Data from JSON ---
  const handleRestoreData = (event) => {
    const file = event.target.files[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const parsedData = JSON.parse(e.target.result);
        
        // Validate JSON structure to prevent app crashes
        if (parsedData.transactions && Array.isArray(parsedData.transactions)) {
          setTransactionsList(parsedData.transactions);
          
          if (parsedData.recurringList && Array.isArray(parsedData.recurringList)) {
            setRecurringList(parsedData.recurringList);
          }
          
          if (parsedData.budget !== undefined) {
            setMonthlyBudget(parseFloat(parsedData.budget));
          }
          
          alert("Success! Your data has been restored perfectly.");
        } else {
          alert("Error: Invalid backup file structure.");
        }
      } catch (error) {
        alert("Error: Could not read the file. Please make sure you selected a valid JSON backup file.");
      }
    };
    reader.readAsText(file);
    // Clear input so the same file can be uploaded again if needed
    event.target.value = '';
  };

  // Filter lists logic
  const filteredTransactions = transactionsList.filter(txn => {
    const matchesType = historyTypeFilter === 'All' || txn.type === historyTypeFilter;
    const matchesCategory = historyCategoryFilter === 'All' || txn.category === historyCategoryFilter;
    
    let matchesDate = false;
    if (historyDateFilter) {
      matchesDate = txn.date === historyDateFilter;
    } else {
      matchesDate = txn.date && typeof txn.date === 'string' && txn.date.startsWith(selectedMonth);
    }

    return matchesType && matchesCategory && matchesDate;
  });

  // Export to CSV Function
  const handleExportCSV = () => {
    if (filteredTransactions.length === 0) {
      alert("No data available to export for the selected filters.");
      return;
    }

    const headers = ['Date', 'Type', 'Description', 'Category', 'Amount (Rs.)'];
    const csvRows = filteredTransactions.map(txn => {
      const safeName = `"${txn.name.replace(/"/g, '""')}"`;
      const typeLabel = txn.type === 'income' ? 'Income' : 'Expense';
      return `${txn.date},${typeLabel},${safeName},${txn.category},${txn.amount}`;
    });

    const csvContent = [headers.join(','), ...csvRows].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    const reportLabel = historyDateFilter ? historyDateFilter : selectedMonth;
    link.setAttribute('download', `SmartWallet_Report_${reportLabel}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Calculations for Analytics
  const txnsThisMonth = transactionsList.filter(txn => 
    txn.date && typeof txn.date === 'string' && txn.date.startsWith(selectedMonth)
  );

  const totalIncome = txnsThisMonth.filter(t => t.type === 'income').reduce((sum, t) => sum + t.amount, 0);
  const totalExpense = txnsThisMonth.filter(t => t.type === 'expense').reduce((sum, t) => sum + t.amount, 0);
  const netBalance = totalIncome - totalExpense;

  // Mini Analytics Widget (Average Daily Spend)
  const todayObj = new Date();
  const selectedDateObj = new Date(selectedMonth + '-01');
  let daysDivisor = 1;
  
  if (todayObj.getFullYear() === selectedDateObj.getFullYear() && todayObj.getMonth() === selectedDateObj.getMonth()) {
    daysDivisor = todayObj.getDate() || 1;
  } else {
    daysDivisor = new Date(selectedDateObj.getFullYear(), selectedDateObj.getMonth() + 1, 0).getDate() || 1;
  }
  const avgDailySpend = totalExpense / daysDivisor;
  const remainingBudget = monthlyBudget - totalExpense;

  const categoryTotals = expenseCategories.reduce((acc, cat) => {
    acc[cat] = txnsThisMonth.filter(e => e.type === 'expense' && e.category === cat).reduce((sum, e) => sum + e.amount, 0);
    return acc;
  }, {});

  let highestCategoryName = 'None';
  let highestCategoryAmount = 0;
  Object.entries(categoryTotals).forEach(([cat, amount]) => {
    if (amount > highestCategoryAmount) {
      highestCategoryAmount = amount;
      highestCategoryName = cat;
    }
  });

  let widgetDisplayName = '';
  let widgetDisplayAmount = 0;
  if (widgetSelection === 'Highest') {
    widgetDisplayName = highestCategoryName !== 'None' ? `${highestCategoryName}` : 'No Expenses';
    widgetDisplayAmount = highestCategoryAmount;
  } else {
    widgetDisplayName = widgetSelection;
    widgetDisplayAmount = categoryTotals[widgetSelection] || 0;
  }

  // Data for Pie Chart
  const chartData = expenseCategories.map(cat => {
    return { name: cat, value: categoryTotals[cat] };
  }).filter(item => item.value > 0);

  const COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6'];
  const isOverBudget = monthlyBudget > 0 && totalExpense > monthlyBudget;

  // Data for Weekly Bar Chart (Last 7 Days)
  const last7DaysData = [...Array(7)].map((_, i) => {
    const d = new Date();
    d.setDate(d.getDate() - (6 - i)); 
    const dateString = d.toISOString().split('T')[0];
    const displayDay = d.toLocaleDateString('en-US', { weekday: 'short' }); 
    
    const dayTotal = transactionsList
      .filter(t => t.type === 'expense' && t.date === dateString)
      .reduce((sum, t) => sum + t.amount, 0);

    return {
      name: displayDay,
      amount: dayTotal,
      fullDate: dateString
    };
  });

  // Pagination Logic
  const totalPages = Math.ceil(filteredTransactions.length / itemsPerPage);
  useEffect(() => {
    if (currentPage > totalPages && totalPages > 0) setCurrentPage(totalPages);
  }, [filteredTransactions.length, currentPage, totalPages]);

  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = filteredTransactions.slice(indexOfFirstItem, indexOfLastItem);

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-10 px-4 antialiased transition-colors duration-300">
      <div className="max-w-4xl mx-auto bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-700 p-6 md:p-8 transition-colors duration-300">
        
        {/* Header Section */}
        <div className="text-center md:text-left md:flex md:justify-between md:items-center border-b border-gray-100 dark:border-gray-700 pb-6">
          <div>
            <div className="flex items-center justify-center md:justify-start gap-3">
              <h1 className="text-3xl font-extrabold text-gray-900 dark:text-white tracking-tight">Smart Wallet</h1>
              <button 
                onClick={() => setIsDarkMode(!isDarkMode)}
                className="p-2 rounded-full bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
                title="Toggle Dark Mode"
              >
                {isDarkMode ? '☀️' : '🌙'}
              </button>
            </div>
            <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Keep your daily income and expenses organized.</p>
          </div>
          <div className="mt-4 md:mt-0">
            <span className="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider block">Current Month Overview</span>
            <input 
              type="month" 
              value={selectedMonth} 
              onChange={(e) => setSelectedMonth(e.target.value)}
              className="mt-1 block w-full bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg p-2 text-sm font-medium text-gray-700 dark:text-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-colors"
            />
          </div>
        </div>

        {/* Analytics Dashboard Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-8">
          <div className="bg-emerald-50 dark:bg-emerald-900/20 rounded-xl p-5 border border-emerald-100 dark:border-emerald-800/50 flex flex-col justify-between transition-colors">
            <div>
              <span className="text-xs font-bold text-emerald-500 dark:text-emerald-400 uppercase tracking-wider block">Total Income</span>
              <h2 className="text-2xl font-black mt-3 text-emerald-600 dark:text-emerald-400">
                Rs. {totalIncome.toLocaleString('en-US', { minimumFractionDigits: 2 })}
              </h2>
            </div>
          </div>

          <div className={`rounded-xl p-5 border transition-all flex flex-col justify-between ${isOverBudget ? 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800/50' : 'bg-rose-50 dark:bg-rose-900/10 border-rose-100 dark:border-rose-800/30'}`}>
            <div>
              <span className="text-xs font-bold text-gray-400 dark:text-gray-500 uppercase tracking-wider block">Total Spent</span>
              <h2 className={`text-2xl font-black mt-3 ${isOverBudget ? 'text-red-600 dark:text-red-400' : 'text-gray-900 dark:text-white'}`}>
                Rs. {totalExpense.toLocaleString('en-US', { minimumFractionDigits: 2 })}
              </h2>
            </div>
            {isOverBudget && (
              <div className="mt-2">
                <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 dark:bg-red-900/50 text-red-800 dark:text-red-300">
                  ⚠️ Budget Exceeded
                </span>
              </div>
            )}
          </div>

          <div className={`rounded-xl p-5 border transition-all flex flex-col justify-between ${netBalance >= 0 ? 'bg-blue-50 dark:bg-blue-900/20 border-blue-100 dark:border-blue-800/50' : 'bg-orange-50 dark:bg-orange-900/20 border-orange-100 dark:border-orange-800/50'}`}>
            <div>
              <span className={`text-xs font-bold uppercase tracking-wider block ${netBalance >= 0 ? 'text-blue-500 dark:text-blue-400' : 'text-orange-500 dark:text-orange-400'}`}>Net Balance</span>
              <h2 className={`text-2xl font-black mt-3 ${netBalance >= 0 ? 'text-blue-600 dark:text-blue-400' : 'text-orange-600 dark:text-orange-400'}`}>
                {netBalance < 0 ? '-' : ''}Rs. {Math.abs(netBalance).toLocaleString('en-US', { minimumFractionDigits: 2 })}
              </h2>
            </div>
          </div>
        </div>

        {/* Analytics Row 2 */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">
          <div className="bg-gray-50 dark:bg-gray-700/40 rounded-xl p-5 border border-gray-100 dark:border-gray-700 flex flex-col justify-between transition-colors">
            <div>
              <span className="text-xs font-bold text-gray-400 dark:text-gray-500 uppercase tracking-wider block">Set Monthly Budget Limit</span>
              <div className="mt-2 relative rounded-md shadow-sm">
                <input 
                  type="number" 
                  placeholder="0.00"
                  value={monthlyBudget || ''} 
                  onChange={(e) => setMonthlyBudget(parseFloat(e.target.value) || 0)}
                  className="w-full bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg p-2.5 text-lg font-semibold text-gray-800 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500 transition-colors"
                />
              </div>
            </div>
          </div>

          <div className="bg-gray-50 dark:bg-gray-700/40 border border-gray-100 dark:border-gray-700 rounded-xl p-5 flex flex-col justify-between transition-colors">
            <div>
              <div className="flex justify-between items-center mb-1">
                <span className="text-xs font-bold text-gray-400 dark:text-gray-500 uppercase tracking-wider block">Expense Insight</span>
                <select
                  value={widgetSelection}
                  onChange={(e) => setWidgetSelection(e.target.value)}
                  className="bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 text-gray-700 dark:text-gray-300 text-xs rounded-md p-1 font-semibold focus:outline-none focus:ring-1 focus:ring-blue-400 cursor-pointer shadow-sm transition-colors"
                >
                  <option value="Highest">Highest Spent</option>
                  {expenseCategories.map(cat => (
                    <option key={cat} value={cat}>{cat}</option>
                  ))}
                </select>
              </div>
              
              <span className="text-sm font-semibold text-gray-800/70 dark:text-gray-300/70 block mt-2">
                {widgetSelection === 'Highest' ? `${widgetDisplayName} (Highest)` : `${widgetDisplayName} Total`}
              </span>
              
              <h2 className="text-2xl font-black text-gray-900 dark:text-white mt-0.5">
                Rs. {widgetDisplayAmount.toLocaleString('en-US', { minimumFractionDigits: 2 })}
              </h2>
            </div>
          </div>
        </div>

        {/* Input Form and Charts Split Panel */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 mt-8 items-start">
          
          {/* Left Column: Form & Recurring */}
          <div className="lg:col-span-5 flex flex-col gap-5">
            
            <div className="bg-gray-50/50 dark:bg-gray-700/30 p-5 rounded-xl border border-gray-100 dark:border-gray-700 transition-colors">
              <div className="flex bg-gray-200 dark:bg-gray-900 rounded-lg p-1 mb-5">
                <button 
                  type="button" 
                  onClick={() => setTxnType('expense')} 
                  className={`flex-1 py-2 text-sm font-bold rounded-md transition-all ${txnType === 'expense' ? 'bg-white dark:bg-gray-800 shadow-sm text-red-600 dark:text-red-400' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'}`}
                >
                  Expense
                </button>
                <button 
                  type="button" 
                  onClick={() => setTxnType('income')} 
                  className={`flex-1 py-2 text-sm font-bold rounded-md transition-all ${txnType === 'income' ? 'bg-white dark:bg-gray-800 shadow-sm text-emerald-600 dark:text-emerald-400' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'}`}
                >
                  Income
                </button>
              </div>

              <form onSubmit={handleAddTransaction} className="space-y-4">
                <div>
                  <input
                    type="text"
                    placeholder={txnType === 'income' ? "Income Source" : "Expense Description"}
                    value={txnName}
                    onChange={(e) => setTxnName(e.target.value)}
                    className="w-full bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg p-3 text-sm text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500 transition-colors"
                  />
                </div>
                <div>
                  <input
                    type="number"
                    placeholder="Amount (Rs.)"
                    value={txnAmount}
                    onChange={(e) => setTxnAmount(e.target.value)}
                    className="w-full bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg p-3 text-sm text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500 transition-colors"
                  />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <select
                    value={txnCategory}
                    onChange={(e) => setTxnCategory(e.target.value)}
                    className="w-full bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg p-3 text-sm text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500 transition-colors"
                  >
                    {activeCategories.map(cat => (
                      <option key={cat} value={cat}>{cat}</option>
                    ))}
                  </select>
                  <input
                    type="date"
                    value={txnDate}
                    onChange={(e) => setTxnDate(e.target.value)}
                    className="w-full bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg p-3 text-sm text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500 transition-colors"
                  />
                </div>
                
                <div className="flex items-center gap-2 mt-2 px-1">
                  <input 
                    type="checkbox" 
                    id="recurring" 
                    checked={isRecurring} 
                    onChange={(e) => setIsRecurring(e.target.checked)} 
                    className="w-4 h-4 text-blue-600 rounded border-gray-300 focus:ring-blue-500" 
                  />
                  <label htmlFor="recurring" className="text-sm font-semibold text-gray-700 dark:text-gray-300 cursor-pointer">
                    Set as Monthly Recurring 🗓️
                  </label>
                </div>

                <button 
                  type="submit" 
                  className={`w-full py-3 text-white font-bold rounded-lg text-sm transition-colors shadow-sm ${txnType === 'income' ? 'bg-emerald-600 hover:bg-emerald-700' : 'bg-blue-600 hover:bg-blue-700'}`}
                >
                  Save Record
                </button>
              </form>
            </div>

            {recurringList.length > 0 && (
              <div className="bg-white dark:bg-gray-800 border border-blue-100 dark:border-blue-900/50 p-4 rounded-xl shadow-sm transition-colors">
                <h4 className="text-xs font-bold text-blue-600 dark:text-blue-400 uppercase tracking-wider mb-3">Active Recurring Subscriptions</h4>
                <div className="space-y-2 max-h-[140px] overflow-y-auto pr-1">
                  {recurringList.map(item => (
                    <div key={item.id} className="flex justify-between items-center bg-gray-50 dark:bg-gray-700/50 p-2 rounded-lg border border-gray-100 dark:border-gray-600">
                      <div>
                        <span className="block text-xs font-bold text-gray-800 dark:text-gray-200">{item.name}</span>
                        <div className="flex items-center gap-2 mt-0.5">
                          <span className={`text-[9px] font-bold px-1.5 py-0.5 rounded-sm ${item.type === 'income' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/50 dark:text-emerald-300' : 'bg-rose-100 text-rose-700 dark:bg-rose-900/50 dark:text-rose-300'}`}>
                            {item.type}
                          </span>
                          <span className="text-[10px] font-semibold text-gray-500 dark:text-gray-400">Rs. {item.amount}/mo</span>
                        </div>
                      </div>
                      <button 
                        onClick={() => setRecurringList(recurringList.filter(r => r.id !== item.id))} 
                        className="text-[10px] font-bold bg-red-100 text-red-600 px-2 py-1 rounded hover:bg-red-200 dark:bg-red-900/40 dark:text-red-400 dark:hover:bg-red-900/60 transition-colors"
                      >
                        Cancel
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Right Column: Charts & Analytics Widgets */}
          <div className="lg:col-span-7 flex flex-col gap-5">
            
            {/* Pie Chart Container */}
            <div className="border border-gray-100 dark:border-gray-700 rounded-xl p-4 flex flex-col items-center justify-center h-[260px] transition-colors bg-white dark:bg-gray-800">
              {chartData.length > 0 ? (
                <div className="w-full h-full relative flex flex-col">
                  <span className="absolute top-0 left-0 text-xs font-bold text-gray-400 dark:text-gray-500">Expense Breakdown ({selectedMonth})</span>
                  <div className="flex-1 mt-4">
                    <ResponsiveContainer width="100%" height="100%">
                      <PieChart>
                        <Pie data={chartData} cx="50%" cy="50%" innerRadius={55} outerRadius={75} paddingAngle={4} dataKey="value">
                          {chartData.map((entry, index) => (
                            <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                          ))}
                        </Pie>
                        <Tooltip formatter={(value) => `Rs. ${value.toFixed(2)}`} contentStyle={{ backgroundColor: isDarkMode ? '#374151' : '#fff', borderColor: isDarkMode ? '#4b5563' : '#ccc', color: isDarkMode ? '#fff' : '#000' }} />
                        <Legend iconType="circle" wrapperStyle={{ fontSize: '12px', color: isDarkMode ? '#d1d5db' : '#374151', marginTop: '10px' }} />
                      </PieChart>
                    </ResponsiveContainer>
                  </div>
                </div>
              ) : (
                <div className="text-center text-gray-400 dark:text-gray-500 text-sm">
                  <p>No expenses found to render visualization maps.</p>
                </div>
              )}
            </div>

            {/* Weekly Bar Chart (Last 7 Days) */}
            <div className="border border-gray-100 dark:border-gray-700 rounded-xl p-4 flex flex-col h-[200px] transition-colors bg-white dark:bg-gray-800">
              <span className="text-xs font-bold text-gray-400 dark:text-gray-500 mb-2">Last 7 Days Expenses</span>
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={last7DaysData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={isDarkMode ? '#374151' : '#f3f4f6'} />
                  <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: isDarkMode ? '#9ca3af' : '#6b7280' }} />
                  <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: isDarkMode ? '#9ca3af' : '#6b7280' }} />
                  <Tooltip 
                    formatter={(value) => [`Rs. ${value.toFixed(2)}`, 'Spent']}
                    labelFormatter={(label) => `Day: ${label}`}
                    contentStyle={{ backgroundColor: isDarkMode ? '#374151' : '#fff', borderColor: isDarkMode ? '#4b5563' : '#e5e7eb', color: isDarkMode ? '#fff' : '#111827', borderRadius: '8px' }}
                    labelStyle={{ color: isDarkMode ? '#9ca3af' : '#6b7280', fontWeight: 'bold', marginBottom: '4px' }}
                  />
                  <Bar dataKey="amount" fill={isDarkMode ? '#60a5fa' : '#3b82f6'} radius={[4, 4, 0, 0]} barSize={28} />
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* Mini Analytics Widgets */}
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-blue-50/70 dark:bg-blue-900/10 p-4 rounded-xl border border-blue-100 dark:border-blue-800/40 flex flex-col justify-center transition-colors">
                <span className="text-[10px] font-bold text-blue-500 dark:text-blue-400 uppercase tracking-wider block">Avg. Daily Spend</span>
                <h3 className="text-xl font-black text-blue-700 dark:text-blue-300 mt-1">
                  Rs. {avgDailySpend.toFixed(2)}
                </h3>
              </div>
              <div className="bg-emerald-50/70 dark:bg-emerald-900/10 p-4 rounded-xl border border-emerald-100 dark:border-emerald-800/40 flex flex-col justify-center transition-colors">
                <span className="text-[10px] font-bold text-emerald-500 dark:text-emerald-400 uppercase tracking-wider block">Remaining Budget</span>
                <h3 className={`text-xl font-black mt-1 ${remainingBudget < 0 ? 'text-red-600 dark:text-red-400' : 'text-emerald-700 dark:text-emerald-300'}`}>
                  {monthlyBudget > 0 ? `Rs. ${remainingBudget.toFixed(2)}` : 'Not Set'}
                </h3>
              </div>
            </div>

          </div>
        </div>

        {/* DYNAMIC ADVANCED FILTER PANEL */}
        <div className="mt-12 border-t border-gray-100 dark:border-gray-700 pt-6 transition-colors">
          <h3 className="text-sm font-bold text-gray-800 dark:text-gray-200 mb-4 flex items-center justify-between">
            <span>Filter Transaction History</span>
          </h3>

          <div className="grid grid-cols-1 sm:grid-cols-4 gap-4 items-end bg-gray-50/70 dark:bg-gray-700/20 p-4 rounded-xl border border-gray-100 dark:border-gray-700 transition-colors">
            <div>
              <label className="text-[11px] font-bold uppercase tracking-wider text-gray-400 dark:text-gray-500 block mb-1">Type</label>
              <select
                value={historyTypeFilter}
                onChange={(e) => setHistoryTypeFilter(e.target.value)}
                className="w-full bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg p-2 text-xs font-semibold text-gray-600 dark:text-gray-300 focus:outline-none transition-colors"
              >
                <option value="All">All Types</option>
                <option value="income">Income Only 🟢</option>
                <option value="expense">Expense Only 🔴</option>
              </select>
            </div>

            <div>
              <label className="text-[11px] font-bold uppercase tracking-wider text-gray-400 dark:text-gray-500 block mb-1">Category</label>
              <select
                value={historyCategoryFilter}
                onChange={(e) => setHistoryCategoryFilter(e.target.value)}
                className="w-full bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg p-2 text-xs font-semibold text-gray-600 dark:text-gray-300 focus:outline-none transition-colors"
              >
                <option value="All">All Categories</option>
                {historyTypeFilter !== 'expense' && incomeCategories.map(cat => <option key={cat} value={cat}>{cat}</option>)}
                {historyTypeFilter !== 'income' && expenseCategories.map(cat => <option key={cat} value={cat}>{cat}</option>)}
              </select>
            </div>

            <div>
              <div className="flex justify-between items-center mb-1">
                <label className="text-[11px] font-bold uppercase tracking-wider text-gray-400 dark:text-gray-500 block">Specific Date</label>
                {historyDateFilter && (
                  <button onClick={() => setHistoryDateFilter('')} className="text-[10px] text-red-500 font-bold hover:underline">Clear</button>
                )}
              </div>
              <input
                type="date"
                value={historyDateFilter}
                onChange={(e) => setHistoryDateFilter(e.target.value)}
                className="w-full bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg p-2 text-xs font-semibold text-gray-600 dark:text-gray-300 focus:outline-none transition-colors"
              />
            </div>

            <button 
              onClick={handleExportCSV}
              className="w-full bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-2 rounded-lg text-xs flex items-center justify-center gap-1 transition-colors shadow-sm h-[34px]"
            >
              📥 Export Filtered CSV
            </button>
          </div>
        </div>

        {/* Tabular History Layout List */}
        <div className="mt-4 overflow-hidden border border-gray-100 dark:border-gray-700 rounded-xl transition-colors">
          {filteredTransactions.length === 0 ? (
            <div className="p-8 text-center text-sm text-gray-400 dark:text-gray-500 bg-gray-50/30 dark:bg-gray-800/50">
              No logged transactions match the specified parameters.
            </div>
          ) : (
            <div className="flex flex-col">
              <div className="divide-y divide-gray-100 dark:divide-gray-700 bg-white dark:bg-gray-800 transition-colors">
                {currentItems.map((txn) => (
                  <div key={txn.id} className="p-4 flex items-center justify-between hover:bg-gray-50/50 dark:hover:bg-gray-700/50 transition-colors">
                    <div>
                      <span className="block text-sm font-semibold text-gray-800 dark:text-gray-200">{txn.name}</span>
                      <div className="flex items-center gap-2 mt-1">
                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                          txn.type === 'income' ? 'bg-emerald-50 text-emerald-600 dark:bg-emerald-900/30 dark:text-emerald-400' : 'bg-rose-50 text-rose-600 dark:bg-rose-900/30 dark:text-rose-400'
                        }`}>
                          {txn.category}
                        </span>
                        <span className="text-xs text-gray-400 dark:text-gray-500">📅 {txn.date}</span>
                      </div>
                    </div>
                    <div className="flex items-center gap-4">
                      <span className={`text-sm font-bold ${txn.type === 'income' ? 'text-emerald-600 dark:text-emerald-400' : 'text-gray-900 dark:text-gray-100'}`}>
                        {txn.type === 'income' ? '+' : '-'} Rs. {txn.amount.toFixed(2)}
                      </span>
                      <button
                        onClick={() => handleDeleteTransaction(txn.id)}
                        className="p-1 px-2.5 rounded-md text-xs font-medium text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/30 transition-colors"
                      >
                        Delete
                      </button>
                    </div>
                  </div>
                ))}
              </div>
              
              {/* Pagination Controls */}
              {totalPages > 1 && (
                <div className="flex items-center justify-between px-4 py-3 bg-gray-50 dark:bg-gray-800 border-t border-gray-100 dark:border-gray-700 transition-colors">
                  <button
                    onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
                    disabled={currentPage === 1}
                    className={`text-sm font-medium px-3 py-1 rounded-md transition-colors ${currentPage === 1 ? 'text-gray-400 dark:text-gray-600 cursor-not-allowed' : 'text-blue-600 dark:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-900/30'}`}
                  >
                    Previous
                  </button>
                  <span className="text-xs font-semibold text-gray-500 dark:text-gray-400">
                    Page {currentPage} of {totalPages}
                  </span>
                  <button
                    onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
                    disabled={currentPage === totalPages}
                    className={`text-sm font-medium px-3 py-1 rounded-md transition-colors ${currentPage === totalPages ? 'text-gray-400 dark:text-gray-600 cursor-not-allowed' : 'text-blue-600 dark:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-900/30'}`}
                  >
                    Next
                  </button>
                </div>
              )}
            </div>
          )}
        </div>

        {/* --- NEW FEATURE: DATA BACKUP & RESTORE PANEL --- */}
        <div className="mt-8 bg-blue-50/50 dark:bg-blue-900/10 border border-blue-100 dark:border-blue-800/50 rounded-xl p-5 transition-colors">
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
              <h3 className="text-sm font-bold text-gray-800 dark:text-gray-200 flex items-center gap-2">
                <span>🛡️</span> Data Security & Backup
              </h3>
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                Securely save your data to your device, or restore it on a different phone/computer.
              </p>
            </div>
            
            <div className="flex flex-wrap items-center gap-3 w-full md:w-auto">
              <button 
                onClick={handleBackupData} 
                className="flex-1 md:flex-none bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg text-xs transition-colors shadow-sm"
              >
                ⬇️ Download Backup
              </button>
              
              <label className="flex-1 md:flex-none bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-2 px-4 rounded-lg text-xs transition-colors shadow-sm cursor-pointer text-center">
                ⬆️ Restore Data
                <input type="file" accept=".json" onChange={handleRestoreData} className="hidden" />
              </label>

              {transactionsList.length > 0 && (
                <button 
                  onClick={handleClearAll} 
                  className="w-full md:w-auto mt-2 md:mt-0 text-xs font-semibold text-red-500 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300 transition-colors p-2"
                >
                  Clear All Data
                </button>
              )}
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}

export default App;